CREATE TABLE tasPassage (
	vleId INTEGER NOT NULL,
	crtId INTEGER NOT NULL,
	psgOrdre INTEGER NOT NULL,
	psgArrivee DOUBLE PRECISION NOT NULL,
	psgDepart DOUBLE PRECISION NOT NULL,
	CONSTRAINT PK_assPassage7 PRIMARY KEY (crtId, vleId)
	);
CREATE TABLE tblAccompagnateurs (
	acpId INTEGER NOT NULL,
	acpNom VARCHAR ( 50 ) NOT NULL,
	acpPrenom VARCHAR ( 50 ) NOT NULL,
	acpAdresse VARCHAR ( 50 ) NOT NULL,
	acpTel VARCHAR ( 20 ) NOT NULL,
	CONSTRAINT PK_tblAccompagnateurs1 PRIMARY KEY (acpId)
	);
CREATE TABLE tblTypesOrganisme (
	tpoId INTEGER NOT NULL,
	tpoDesignation SMALLINT NOT NULL,
	CONSTRAINT PK_tblTransports9 PRIMARY KEY (tpoId)
	);
CREATE TABLE tasParticipants (
	crtId INTEGER NOT NULL,
	cltId INTEGER NOT NULL,
	ptiAccompte INTEGER NOT NULL,
	ptiVersement INTEGER NOT NULL,
	ptiRemise INTEGER NOT NULL,
	CONSTRAINT PK_tasParticipants8 PRIMARY KEY (cltId, crtId)
	);
CREATE TABLE tblCircuits (
	crtId INTEGER NOT NULL,
	crtIntitule VARCHAR ( 50 ) NOT NULL,
	crtPrix INTEGER NOT NULL,
	crtPlaceTotale INTEGER NOT NULL,
	acpId INTEGER NOT NULL,
	CONSTRAINT PK_tblCircuits5 PRIMARY KEY (crtId)
	);
CREATE TABLE tblOrganismes (
	orgId INTEGER NOT NULL,
	orgNom VARCHAR ( 50 ) NOT NULL,
	orgAdresse VARCHAR ( 100 ) NOT NULL,
	orgTel VARCHAR ( 20 ) NOT NULL,
	vleId INTEGER NOT NULL,
	tpoId INTEGER NOT NULL,
	CONSTRAINT PK_tblOrganismes10 PRIMARY KEY (orgId)
	);
CREATE TABLE tblClients (
	cltId INTEGER NOT NULL,
	cltNom VARCHAR ( 50 ) NOT NULL,
	cltPrenom VARCHAR ( 50 ) NOT NULL,
	cltAdresse VARCHAR ( 50 ) NOT NULL,
	cltTel VARCHAR ( 50 ) NOT NULL,
	CONSTRAINT PK_tblClients0 PRIMARY KEY (cltId)
	);
CREATE TABLE tblVilles (
	vleId INTEGER NOT NULL,
	vleNom VARCHAR ( 50 ) NOT NULL,
	CONSTRAINT PK_tblVilles2 PRIMARY KEY (vleId)
	);
CREATE TABLE tasContactes (
	orgId INTEGER NOT NULL,
	crtId INTEGER NOT NULL,
	vleId INTEGER NOT NULL,
	CONSTRAINT PK_tasContactes11 PRIMARY KEY (crtId, vleId, orgId)
	);
ALTER TABLE tasPassage ADD CONSTRAINT FK_assPassage10 FOREIGN KEY (vleId) REFERENCES tblVilles (vleId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tasPassage ADD CONSTRAINT FK_assPassage11 FOREIGN KEY (crtId) REFERENCES tblCircuits (crtId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tasParticipants ADD CONSTRAINT FK_tasParticipants13 FOREIGN KEY (crtId) REFERENCES tblCircuits (crtId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tasParticipants ADD CONSTRAINT FK_tasParticipants14 FOREIGN KEY (cltId) REFERENCES tblClients (cltId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tblCircuits ADD CONSTRAINT FK_tblCircuits15 FOREIGN KEY (acpId) REFERENCES tblAccompagnateurs (acpId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tblOrganismes ADD CONSTRAINT FK_tblOrganismes20 FOREIGN KEY (tpoId) REFERENCES tblTypesOrganisme (tpoId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tblOrganismes ADD CONSTRAINT FK_tblOrganismes17 FOREIGN KEY (vleId) REFERENCES tblVilles (vleId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tasContactes ADD CONSTRAINT FK_tasContactes18 FOREIGN KEY (orgId) REFERENCES tblOrganismes (orgId)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE tasContactes ADD CONSTRAINT FK_tasContactes19 FOREIGN KEY (crtId, vleId) REFERENCES tasPassage (crtId, vleId)  ON DELETE NO ACTION ON UPDATE NO ACTION;

