/*
 * OptionsFrame.java
 *
 * Created on 25 August 2005, 12:00
 */

//package XmlRpcDebugger;

/**
 *
 * @author  Meredydd
 */
public class OptionsFrame extends javax.swing.JFrame {
    
    /** Creates new form OptionsFrame */
    public OptionsFrame() {
        initComponents();
        setBounds(new java.awt.Rectangle(200,200,350,220));
        reload();
    }
    
    private void reload()
    {
        urlField.setText(Main.properties.getProperty("xmlrpc.url"));
        prefixField.setText(Main.properties.getProperty("xmlrpc.prefix"));
        suffixField.setText(Main.properties.getProperty("xmlrpc.suffix"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prefixField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        suffixField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Options");
        setResizable(false);
        jLabel1.setText("URL:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 34, 20);

        getContentPane().add(urlField);
        urlField.setBounds(70, 20, 260, 21);

        jLabel2.setText("Prefix:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 50, 20);

        prefixField.setText("[]");
        getContentPane().add(prefixField);
        prefixField.setBounds(70, 60, 260, 21);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        jLabel3.setText("The prefix array is prepended to all argument lists.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 310, 20);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        jLabel4.setText("The suffix array is appended to all argument lists.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 310, 20);

        suffixField.setText("[]");
        getContentPane().add(suffixField);
        suffixField.setBounds(70, 110, 260, 21);

        jLabel5.setText("Suffix:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 50, 20);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        getContentPane().add(saveButton);
        saveButton.setBounds(90, 160, 73, 25);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        getContentPane().add(cancelButton);
        cancelButton.setBounds(180, 160, 73, 25);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        reload();
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Main.properties.put("xmlrpc.url", urlField.getText());
        Main.properties.put("xmlrpc.prefix", prefixField.getText());
        Main.properties.put("xmlrpc.suffix", suffixField.getText());
        Main.save();
        setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField prefixField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField suffixField;
    private javax.swing.JTextField urlField;
    // End of variables declaration//GEN-END:variables
    
}
